package com.huanghehua.www.orm.model;


import com.huanghehua.www.orm.handler.SqlHandler;

import java.sql.Connection;
import java.sql.Statement;

/**
 * 用于{@link SqlHandler#handle}的不可变value对象
 * 将多参数封装到一个实体类中，利于维护。<br/>
 *
 * @author timeboy
 * @version 1.0.0
 * @date 2023/03/22
 */
public class PreparedStatementConfiguration {
    /**
     * 指定数据源的连接资源
     */
    private final Connection connection;

    /**
     * 指定映射文件中的SQL
     */
    private final String prototypeSql;

    /**
     * 是否返回自增主键
     */
    private final int autoGeneratedKeys;

    public PreparedStatementConfiguration(Connection connection, String prototypeSql) {
        this.connection = connection;
        this.prototypeSql = prototypeSql;
        this.autoGeneratedKeys = Statement.NO_GENERATED_KEYS;
    }

    public PreparedStatementConfiguration(Connection connection, String prototypeSql, int autoGeneratedKeys) {
        this.connection = connection;
        this.prototypeSql = prototypeSql;
        this.autoGeneratedKeys = autoGeneratedKeys;
    }
    public Connection getConnection() {
        return connection;
    }

    public String getPrototypeSql() {
        return prototypeSql;
    }

    public int getAutoGeneratedKeys() {
        return autoGeneratedKeys;
    }
}
